#!/usr/bin/env python3

from sys import *
import getopt
import time

from Sockets.socket_file import SocketInteractionPython
from socket_file import SocketInteraction
from Level1.level1 import level1
from Level8.level8 import level8
from General_comportement.layAnEgg import layAnEgg


def go_in_state(socket):
    level = 1
    while (level < 8):
        level = level1(level, socket)
        print("\n------------------------------------------------------------")
        print("LEVEL " + str(level) + "  REACHED ")
        print("------------------------------------------------------------\n")
        layAnEgg(level, socket)
    print("Level 8 !")
    level8(socket)


def connection(port, name, machine, python):
    if python is True:
        socket = SocketInteractionPython(str(machine), port, str(name))
    else:
        socket = SocketInteraction(str(machine), port, str(name))
    return (socket)


def print_usage():
    print("USAGE: ./zappy_ai -p port -n name -h machine")
    print("\tport\tis the port number")
    print("\tname\tis the name of the team")
    print("\tmachine\tis the name of the machine; localhost by default")


def main():
    my_argv = argv[1:]
    port = 0
    name = ""
    machine = "127.0.0.1"
    python = False
    try:
        optlist, args = getopt.getopt(my_argv, "p:n:h:s", ["help"])
    except getopt.GetoptError as err:
        print(err)
        print_usage()
        exit(84)
    if (args != []):
        print_usage()
        exit(84)
    for opt, val in optlist:
        if opt == "--help":
            print_usage()
            exit(0)
        if opt == "-p":
            try:
                port = int(val)
            except:
                print_usage()
                exit(84)
        elif opt == "-n":
            name = val
        elif opt == "-h":
            machine = val
        elif opt == "-s":
            python = True
        else:
            assert False, "unhandled option"
    if (port == 0 or name == ""):
        print_usage()
        exit(84)
    socket = connection(port, name, machine, python)
    go_in_state(socket)

if __name__ == '__main__':
    main()
