#!/usr/bin/env python3

#
# EPITECH PROJECT, 2018
# PSU_zappy_2017
# File description:
# zappy_ai
#

import signal
import time

from socket import Socket

if __name__ == "__main__":
    try:
        socket = Socket("127.0.0.1", 4242, "Yellow")
        while (True):
            socket.Inventory()
            socket.Forward()
            time.sleep(0.2)
            print(socket.GetServerResponse())
    except KeyboardInterrupt as e:
        print("\nProgram interrupt with CTRL+C")
        exit(0)
